services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: space-movies-backend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/space-movies
      - OMDB_API_KEY=${OMDB_API_KEY}
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=20
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    networks:
      space-movies-network:
        aliases:
          - backend.local
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        VITE_API_URL: /api
    container_name: space-movies-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      space-movies-network:
        aliases:
          - frontend.local
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:latest
    container_name: space-movies-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      space-movies-network:
        aliases:
          - mongo.local
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    container_name: space-movies-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      space-movies-network:
        aliases:
          - redis.local
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  space-movies-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
